export interface NavItem {
  label: string;
  href: string;
  icon: string;
}

export const navItemsByRole: Record<string, NavItem[]> = {
  admin_school: [
    { label: "Tableau de bord", href: "/admin", icon: "LayoutDashboard" },
    { label: "Élèves", href: "/admin/students", icon: "GraduationCap" },
    { label: "Enseignants", href: "/admin/teachers", icon: "Users" },
    { label: "Parents", href: "/admin/parents", icon: "UserCog" },
    { label: "Classes", href: "/admin/classes", icon: "School" },
    { label: "Matières", href: "/admin/subjects", icon: "BookOpen" },
    { label: "Affectations", href: "/admin/assignments", icon: "Link" },
    { label: "Devoirs", href: "/admin/devoirs", icon: "ClipboardCheck" },
    { label: "TD/TP", href: "/admin/td", icon: "CalendarCheck" },
    { label: "Cours", href: "/admin/courses", icon: "BookOpen" },
    { label: "Programme", href: "/admin/programme", icon: "BookOpen" },
    { label: "Emploi du temps", href: "/admin/schedule", icon: "CalendarRange" },
    { label: "Présences", href: "/admin/attendance", icon: "Calendar" },
    { label: "Années scolaires", href: "/admin/academic-years", icon: "CalendarRange" },
    { label: "Paiements", href: "/admin/payments", icon: "CreditCard" },
    { label: "Bulletins", href: "/admin/reports", icon: "FileText" },
    { label: "Messages", href: "/admin/messages", icon: "MessageSquare" },
    { label: "Paramètres", href: "/admin/school", icon: "Settings" },
  ],
  super_admin: [
    { label: "Vue Globale", href: "/super-admin", icon: "Globe" },
    { label: "Tableau de bord (École)", href: "/admin", icon: "LayoutDashboard" },
    { label: "Élèves", href: "/admin/students", icon: "GraduationCap" },
    { label: "Enseignants", href: "/admin/teachers", icon: "Users" },
    { label: "Parents", href: "/admin/parents", icon: "UserCog" },
    { label: "Classes", href: "/admin/classes", icon: "School" },
    { label: "Matières", href: "/admin/subjects", icon: "BookOpen" },
    { label: "Affectations", href: "/admin/assignments", icon: "Link" },
    { label: "Devoirs", href: "/admin/devoirs", icon: "ClipboardCheck" },
    { label: "TD/TP", href: "/admin/td", icon: "CalendarCheck" },
    { label: "Cours", href: "/admin/courses", icon: "BookOpen" },
    { label: "Programme", href: "/admin/programme", icon: "BookOpen" },
    { label: "Présences", href: "/admin/attendance", icon: "Calendar" },
    { label: "Emploi du temps", href: "/admin/schedule", icon: "CalendarRange" },
    { label: "Années scolaires", href: "/admin/academic-years", icon: "CalendarRange" },
    { label: "Paiements", href: "/admin/payments", icon: "CreditCard" },
    { label: "Bulletins", href: "/admin/reports", icon: "FileText" },
    { label: "Messages", href: "/admin/messages", icon: "MessageSquare" },
    { label: "Paramètres", href: "/admin/school", icon: "Settings" },
  ],
  teacher: [
    { label: "Tableau de bord", href: "/teacher", icon: "LayoutDashboard" },
    { label: "Notes", href: "/teacher/grades", icon: "ClipboardList" },
    { label: "Présences", href: "/teacher/attendance", icon: "Calendar" },
    { label: "Mes classes", href: "/teacher/classes", icon: "School" },
    { label: "Emploi du temps", href: "/teacher/schedule", icon: "CalendarRange" },
    { label: "Programme", href: "/teacher/programme", icon: "BookOpen" },
    { label: "Devoirs", href: "/teacher/assignments", icon: "ClipboardCheck" },
    { label: "TD/TP", href: "/teacher/td", icon: "CalendarCheck" },
    { label: "Cours", href: "/teacher/courses", icon: "BookOpen" },
    { label: "Messages", href: "/teacher/messages", icon: "MessageSquare" },
  ],
  parent: [
    { label: "Tableau de bord", href: "/parent", icon: "LayoutDashboard" },
    { label: "Mes enfants", href: "/parent/children", icon: "Users" },
    { label: "Paiements", href: "/parent/payments", icon: "CreditCard" },
    { label: "Messages", href: "/parent/messages", icon: "MessageSquare" },
    { label: "Assistant IA", href: "/parent/chatbot", icon: "Bot" },
    { label: "Programme", href: "/parent/programme", icon: "BookOpen" },
    { label: "TD/TP", href: "/parent/td", icon: "CalendarCheck" },
    { label: "Emploi du temps", href: "/parent/schedule", icon: "CalendarRange" },
  ],
  student: [
    { label: "Tableau de bord", href: "/student", icon: "LayoutDashboard" },
    { label: "Mes notes", href: "/student/grades", icon: "ClipboardList" },
    { label: "Programme", href: "/student/programme", icon: "BookOpen" },
    { label: "Devoirs", href: "/student/assignments", icon: "ClipboardCheck" },
    { label: "TD/TP", href: "/student/td", icon: "CalendarCheck" },
    { label: "Emploi du temps", href: "/student/schedule", icon: "CalendarRange" },
    { label: "Cours", href: "/student/courses", icon: "BookOpen" },
    { label: "Messages", href: "/student/messages", icon: "MessageSquare" },
  ],
};